### ISSUE TITLE
feat: Extensions

### ISSUE THREAD

**Issue by Dhravya** [cake-cutter/cc#13]
Extensions will be a set of pre-defined cakes.

Basically, this will allow users to "stack" cakes, smaller cakefiles

Extensions will be a list of other published cakes or maybe even local cakes.
```toml
[metadata]
name = "..."
description = "..."
exts = ["readme","license"]
```
these exts will be run before the actual cake. So you don't have to write extra code. and ask the questions.
