### ISSUE TITLE
Commands are run in seemingly random order

### ISSUE THREAD

**Issue by kekda-py** [cake-cutter/cc#9]
currently the commands run on random (we were unaware of that). So fixing that by adding a list
```toml
[commands]
"git init" = ["1","true"]
#              ^ order
```

**Comment by Dhravya** [comment]
Instead of adding a list, is there a way to parse in order the commands are written?

**Comment by kekda-py** [comment]
yeah I thought that It'll automatically do that (the parser) but naah

**Comment by Dhravya** [comment]
Here's the new syntax for the cakefiles
```toml
[commands]
1 = [
  "go mod init {{module}}","true"
]
```
